services:
  kalman-filter:
    container_name: kalman-filter
    build: ./src
    volumes:
      - ./src:/main
    command: tail -F anything.js
    # command: g++ main.cpp -std=c++20 -o temp_pred_app.out
    # command: ./temp_pred_app.out