FROM gcc:latest

WORKDIR /main

# RUN git clone https://github.com/lava/matplotlib-cpp.git
# RUN apt-get update && apt-get install python3.10
# RUN apt-get install python3-matplotlib -y && apt-get install python3-numpy -y

RUN git clone https://gitlab.com/libeigen/eigen.git